### PR TITLE
Fix membership form bug.

### PR DESCRIPTION
**Pull request by eschlange**
* Updated the membership form to use group_id rather than params[:id].

[Finished #91010606]

### CODE REVIEW

**Comment by gwensmu** [comment]
is it the case that its an invalid group because in this case, the group_id has not yet been set since the membership has not been created?

**Comment by eschlange** [comment]
I'm not sure what you're asking.

**Comment by gwensmu** [comment]
@eschlange you wrote that you updated the form to " to use invalid group." This doesn't make sense to me in the context of the bug and the change.

**Comment by eschlange** [comment]
@gwensmu mistyped. fixed the commit message.

**Comment by gwensmu** [comment]
great! 💻🎪

**Pull request merged**
